version: "3.5"

services:

  sequence-retrieval:

    image: sequence-retrieval:${SEQUENCE_RETRIEVAL_TAG:-latest}

    networks:
      external:

    ports:
      - 8080:8080

    volumes:
      - type: bind
        source: ${FASTA_FILES_DIR}
        target: /sequenceFiles
        read_only: true

    environment:

      # Genomic Sequence Config
      GENOMIC_FASTA_FILE: ${GENOMIC_FASTA_FILE:-/sequenceFiles/Genome.fa}
      GENOMIC_INDEX_FILE: ${GENOMIC_INDEX_FILE:-/sequenceFiles/Genome.fa.fai}
      GENOMIC_MAX_SEQUENCES_PER_REQUEST: ${GENOMIC_MAX_SEQUENCES_PER_REQUEST:-10}
      GENOMIC_MAX_TOTAL_BASES_PER_REQUEST: ${GENOMIC_MAX_TOTAL_BASES_PER_REQUEST:-10000}
      GENOMIC_DISALLOW_REVERSE_COMPLEMENT: ${GENOMIC_DISALLOW_REVERSE_COMPLEMENT:-false}

      # Protein Sequence Config
      PROTEIN_FASTA_FILE: ${PROTEIN_FASTA_FILE:-/sequenceFiles/Protein.fa}
      PROTEIN_INDEX_FILE: ${PROTEIN_INDEX_FILE:-/sequenceFiles/Protein.fa.fai}
      PROTEIN_MAX_SEQUENCES_PER_REQUEST: ${PROTEIN_MAX_SEQUENCES_PER_REQUEST:-3}
      PROTEIN_MAX_TOTAL_BASES_PER_REQUEST: ${PROTEIN_MAX_TOTAL_BASES_PER_REQUEST:-10e6}
      PROTEIN_DISALLOW_REVERSE_COMPLEMENT: ${PROTEIN_DISALLOW_REVERSE_COMPLEMENT:-true}

networks:
  # external network used for containers that need to reach outside
  external:

