version: "3.5"

services:

  sequence-retrieval:

    image: sequence-retrieval:${SEQUENCE_RETRIEVAL_TAG:-latest}

    networks:
      external:
      monitoring-ext:
      traefik:

    volumes:
      - type: bind
        source: ${FASTA_FILES_DIR}
        target: /sequenceFiles
        read_only: true

    environment:

      # Genomic Sequence Config
      GENOMIC_FASTA_FILE: ${GENOMIC_FASTA_FILE:-/sequenceFiles/Genome.fa}
      GENOMIC_INDEX_FILE: ${GENOMIC_INDEX_FILE:-/sequenceFiles/Genome.fa.fai}
      GENOMIC_MAX_SEQUENCES_PER_REQUEST: ${GENOMIC_MAX_SEQUENCES_PER_REQUEST:-10}
      GENOMIC_MAX_TOTAL_BASES_PER_REQUEST: ${GENOMIC_MAX_TOTAL_BASES_PER_REQUEST:-1000}

      # Protein Sequence Config
      PROTEIN_FASTA_FILE: ${PROTEIN_FASTA_FILE:-/sequenceFiles/Protein.fa}
      PROTEIN_INDEX_FILE: ${PROTEIN_INDEX_FILE:-/sequenceFiles/Protein.fa.fai}
      PROTEIN_MAX_SEQUENCES_PER_REQUEST: ${PROTEIN_MAX_SEQUENCES_PER_REQUEST:-3}
      PROTEIN_MAX_TOTAL_BASES_PER_REQUEST: ${PROTEIN_MAX_TOTAL_BASES_PER_REQUEST:-10e6}
      PROTEIN_DISALLOW_REVERSE_COMPLEMENT: ${PROTEIN_DISALLOW_REVERSE_COMPLEMENT:-true}

    labels:
      - "prometheus.scrape_enabled=true"
      - "com.centurylinklabs.watchtower.enable=${DATA_WATCHTOWER:-false}"
      - "traefik.http.services.${TRAEFIK_DATA_ROUTER:-sequenceretrieval-dev}.loadbalancer.server.port=${SR_SERVER_PORT:-8080}"
      - "traefik.http.routers.${TRAEFIK_DATA_ROUTER:-sequenceretrieval-dev}.rule=Host(`${TRAEFIK_DATA_HOST:-sequenceretrieval-dev.local.apidb.org}`)"
      - "traefik.http.routers.${TRAEFIK_DATA_ROUTER:-sequenceretrieval-dev}.tls=true"
      - "traefik.http.routers.${TRAEFIK_DATA_ROUTER:-sequenceretrieval-dev}.entrypoints=${TRAEFIK_ENTRYPOINTS:-local}"
      - "traefik.docker.network=traefik"

networks:
  # external network used for containers that need to reach outside
  external:
  traefik:
    external: true
  monitoring-ext:
    external: true

