= Example Containerized Async Service
:toc:
:source-highlighter: highlightjs
:icons: font
// Github specifics
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
Elizabeth Paige Harper <epharper@upenn.edu>
v1.0.0

This repository is a template for and demonstration of creating asynchronous
job processing services utilizing VEuPathDB's
https://github.com/VEuPathDB/lib-jaxrs-container-core[container infrastructure]
and https://github.com/VEuPathDB/lib-compute-platform[async compute platform].

For additional information about the components this project is built upon, see
the following projects:

* https://github.com/VEuPathDB/example-jaxrs-container-service[Example Container Service]
* https://github.com/VEuPathDB/lib-jaxrs-container-core[Container Service Core]
* https://github.com/VEuPathDB/lib-compute-platform[Async Compute Platform]

== Running the Example

=== Prerequisites

* https://docs.docker.com/engine/[Docker]
* https://docs.docker.com/compose/[Docker Compose]

=== Start Up

[source, shell]
----
$ make example-clean
$ make example-build
$ make example-run
----

=== Using the Service

https://veupathdb.github.io/example-async-compute-service/api.html[API Documentation]

Using `curl`, https://www.postman.com/[Postman], or your favorite API request
tool, the following actions may be performed on the example service:

. <<Job Submission,Submitting string reversal jobs>>
. <<Job Status Check,Check the status of your job>>
. Get the output files from your job
. Download the output file from your job

==== Job Submission

The example project offers one job type under the endpoint `/reverse` which
simply reverses the given input string.

The input is taken as a JSON object with an `"input"` field containing the text
to reverse.

.Example Input
[source, json]
----
{
  "input": "racecar"
}
----

Once the job is accepted, the API will return a JSON object containing
information about the submitted job.  The key piece of information in this
response is the `"jobID"` field which is the ID of the created job that can be
used in requests to other API endpoints to retrieve information about the job
and the job's results.

.Example Response
[source, json]
----
{
  "jobID": "6c3ac2cc4489e81857e1e2290523a505",
  "status": "queued",
  "queuePosition": 0
}
----

==== Job Status Check

Once a job has been submitted, the API may be used to check on the status of the
job.  In a more realistic situation, this endpoint could be used to poll the API
waiting for the job's status to be updated to a completion status.

In the example API, a job's status/details may be retrieved using the
`/jobs/{job-id}` endpoint.  In this endpoint the `{job-id}` variable should be
replaced with the ID of the job returned on job submission.

.Example Response
[source, json]
----
{
  "jobID": "6c3ac2cc4489e81857e1e2290523a505",
  "status": "complete"
}
----

==== Job File Listing

A completed job will have result files associated with it.  These files may be
listed using the `/jobs/{job-id}/files` endpoint.

.Example Response
[source, json]
----
[
  "output"
]
----

==== Job File Download



=== RabbitMQ

The example uses a RabbitMQ image with the management plugin.  This means that
it is possible to view the queues and their state from the browser by navigating
to http://localhost:9002 when the example docker-compose stack is online.

The credentials for the management plugin login are `demouser` / `demopass` by
default, but are configured via the `RABBITMQ_DEFAULT_USER` and
`RABBITMQ_DEFAULT_PASS` environment variables set in the
https://github.com/VEuPathDB/example-async-compute-service/blob/master/docker-compose.example.yml[example docker-compose config].


=== S3 / MinIO

The S3 store backing the example project is https://min.io[MinIO].  This MinIO
instance may be accessed and managed via a web interface by navigating to
http://localhost:9001 when the example docker-compose stack is online.

The credentials for the web interface are `demouser` / `demopass` by default,
but are configured via the `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD`
environment variables set in the
https://github.com/VEuPathDB/example-async-compute-service/blob/master/docker-compose.example.yml[example docker-compose config].


== Using this Template

=== Defining Queues