= Service for sequence retrieval

== Running locally

To build the service in place (produce a jar), run:
```
make jar
```

To build a runnable "test" docker image, run:
```
make docker
```

To execute unit tests, run:
```
make test
```

The service can be brought up via docker, using the sample docker-compose and env files, like this:
```
make docker-compose-clean
make docker-compose-build
make docker-compose-run
```

You might need a traefik to run:
```
cp ~/dev/docker-traefik/docker-compose.yml docker-compose/traefik.yml
docker compose -f  docker-compose/traefik.yml -f docker-compose/docker-compose.yml -f docker-compose/docker-compose.dev.yml up
```

== Configuration

Configuration is handled via docker-compose.yml, which reads values from environment (provided by default by .env or you may specify another file)

Please see `docker-compose/docker-compose.test.yml` and `.env.test` for test configuration.  The file `docker-compose/docker-compose.prod.yml` will be used for production configuration.

== Example queries

See `cURL` scripts in the `src/test/query` folder.  Note: some of these may no longer work.
