= Service for sequence retrieval

== Running locally

Environment/dependency setup for local development can be done via the command
`make install-dev-env`.  This will install the dependencies required to build the
project.

After the environment has been set up, the project can be built, tested, and
packaged using `./gradlew shadowJar`.

Starting the server can be done by running `java -jar build/libs/service-sequence-retrieval-1.0.0-all.jar`.

Export user and account DB credentials like documented in https://github.com/VEuPathDB/lib-jaxrs-container-core[Core container library].

== Configuration
Edit the file `config.json` 's default contents:
```
{
  "referenceSequenceSpecs": [
    {
      "name": "genomic",
      "fasta": "src/test/resources/veupathdb/service/sequence/reference/Genome.fa",
      "index": "src/test/resources/veupathdb/service/sequence/reference/Genome.fa.fai",
      "maxSequencesPerRequest": 10,
      "maxTotalBasesPerRequest": 1000
...
```

List one entry per sequence, providing paths to fasta and index files. The name parameter corresponds to URL of the sequence for retrieval.

== Example queries

See `cURL` scripts in the `src/test/query` folder.
