#%RAML 1.0 Library

types:
  # Type name determines the name of the Java class that will be generated.

  JobResponse:
    type: object
    properties:
      jobID:
        type: string
        minLength: 32
        maxLength: 32
        pattern: '^[\dA-Fa-f]{32}$'
      status:
        type: JobStatus
      queuePosition?:
        type: integer
        format: int32
      created?:
        type: datetime
        description: Time the job was submitted. Absent if not yet available.
      started?:
        type: datetime
        description: Time a worker picked up the job. Absent if not yet started.
      finished?:
        type: datetime
        description: Time the job finished. Absent if not yet finished.
    additionalProperties: false

  JobDataResponse:
    type: any

  JobStatus:
    type: string
    enum:
      - queued
      - in-progress
      - complete
      - failed
      - expired
