#%RAML 1.0 Library


uses:
  common: ../../common.raml

types:
  SequenceGenomicPostRequest:
    additionalProperties: false
    properties:
      features:
        type: array
        items: common.Feature
      deflineFormat:
        type: common.DeflineFormat
        default: "region_only"
      forceStrandedness:
        type: boolean
        default: false


  SequenceGenomicPostResponse: common.PlainTextFastaResponse
