#%RAML 1.0 Library


uses:
  common: ../../common.raml

types:
  SequenceGenomicPostRequest:
    additionalProperties: false
    properties:
      features:
        type: array
        items: common.Feature
      deflineFormat: common.DeflineFormat
      forceStrandedness:
        type: boolean
        default: false
      basesPerLine?: integer

  SequenceGenomicPostResponse: common.PlainTextFastaResponse
