version: '3.8'

services:
  minio:
    image: minio/minio
    command: server --console-address ':9001' /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: demouser
      MINIO_ROOT_PASSWORD: demopass

  minio-create-buckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 1;
      /usr/bin/mc alias set minioc http://minio:9000 demouser demopass;
      /usr/bin/mc mb minioc/demobucket;
      /usr/bin/mc policy set public minioc/demobucket;
      exit 0;
      "
  queue-db:
    image: postgres:14.3-alpine3.16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: demopass
      POSTGRES_DB: demodb

  queue:
    image: rabbitmq:3.10.5-management-alpine
    ports:
      - "9002:15672"
    environment:
      RABBITMQ_DEFAULT_USER: demouser
      RABBITMQ_DEFAULT_PASS: demopass

  service:
    build:
      dockerfile: Dockerfile
      context: ..
    ports:
      - "8080:8080"
    depends_on:
      - minio
      - queue
      - queue-db
    environment:
      # Queue Platform Postgres
      QUEUE_DB_NAME: demodb
      QUEUE_DB_HOST: queue-db
      QUEUE_DB_PORT: 5432
      QUEUE_DB_USERNAME: demouser
      QUEUE_DB_PASSWORD: demopass
      QUEUE_DB_POOL_SIZE: 10

      # Queue Platform RabbitMQ
      JOB_QUEUE_USERNAME: demouser
      JOB_QUEUE_PASSWORD: demopass
      JOB_QUEUE_HOST: queue
      JOB_QUEUE_PORT: 5672
      JOB_QUEUE_WORKERS: 5

      # Queue Platform Minio
      S3_HOST: minio
      S3_BUCKET: demobucket
      S3_ACCESS_TOKEN: demouser
      S3_SECRET_KEY: demopass
      S3_PORT: 9000

      # Job Settings
      JOB_CACHE_TIMEOUT_DAYS: 30
