version: "3.5"

volumes:
  sequence-retrieval-db:

services:

  minio:
    image: minio/minio
    command: server --console-address ':9001' /data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - internal
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_TOKEN}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}

  minio-create-buckets:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - internal
    environment:
      MINIO_USER: ${S3_ACCESS_TOKEN?required}
      MINIO_PASS: ${S3_SECRET_KEY?required}
      MINIO_BUCKET: ${S3_BUCKET?required}
    entrypoint: >
      /bin/sh -c "
      sleep 1;
      /usr/bin/mc alias set minioc http://minio:9000 $$MINIO_USER $$MINIO_PASS;
      /usr/bin/mc mb minioc/$$MINIO_BUCKET;
      /usr/bin/mc policy set public minioc/$$MINIO_BUCKET;
      exit 0;
      "

  queue-db:
    image: postgres:14.3-alpine3.16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgresuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB:-queuedb}
    volumes:
      - sequence-retrieval-db:/var/lib/postgresql/data
    networks:
      - internal
    labels:
      - "com.centurylinklabs.watchtower.enable=${POSTGRES_WATCHTOWER:-false}"
      - "traefik.enable=false"

  queue:
    image: rabbitmq:3.10.5-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${QUEUE_USER:-rabbituser}
      RABBITMQ_DEFAULT_PASS: ${QUEUE_PASS}
    networks:
      - internal
    labels:
      - "com.centurylinklabs.watchtower.enable=${RABBITMQ_WATCHTOWER:-false}"
      - "traefik.enable=false"

  sequence-retrieval:
    build:
      dockerfile: Dockerfile
      context: ..

    depends_on:
      - queue-db
      - queue
    networks:
      internal:
    volumes:
      - type: bind
        source: ${FASTA_FILES_DIR}
        target: /sequenceFiles
        read_only: true

    environment:
      # Genomic Sequence Config
      GENOMIC_FASTA_FILE: ${GENOMIC_FASTA_FILE:-/sequenceFiles/Genome.fa}
      GENOMIC_INDEX_FILE: ${GENOMIC_INDEX_FILE:-/sequenceFiles/Genome.fa.fai}
      GENOMIC_MAX_SEQUENCES_PER_REQUEST: ${GENOMIC_MAX_SEQUENCES_PER_REQUEST:-10}
      GENOMIC_MAX_TOTAL_BASES_PER_REQUEST: ${GENOMIC_MAX_TOTAL_BASES_PER_REQUEST:-1000}
      GENOMIC_DISALLOW_REVERSE_COMPLEMENT: ${GENOMIC_DISALLOW_REVERSE_COMPLEMENT:-false}

      # Protein Sequence Config
      PROTEIN_FASTA_FILE: ${PROTEIN_FASTA_FILE:-/sequenceFiles/AnnotatedProteins.fa}
      PROTEIN_INDEX_FILE: ${PROTEIN_INDEX_FILE:-/sequenceFiles/AnnotatedProteins.fa.fai}
      PROTEIN_MAX_SEQUENCES_PER_REQUEST: ${PROTEIN_MAX_SEQUENCES_PER_REQUEST:-3}
      PROTEIN_MAX_TOTAL_BASES_PER_REQUEST: ${PROTEIN_MAX_TOTAL_BASES_PER_REQUEST:-10e6}
      PROTEIN_DISALLOW_REVERSE_COMPLEMENT: ${PROTEIN_DISALLOW_REVERSE_COMPLEMENT:-true}

      # Queue Platform Postgres
      QUEUE_DB_NAME: ${POSTGRES_DB:-queuedb}
      QUEUE_DB_USERNAME: ${POSTGRES_USER:-postgresuser}
      QUEUE_DB_PASSWORD: ${POSTGRES_PASS}
      QUEUE_DB_HOST: ${POSTGRES_HOST:-queue-db}
      QUEUE_DB_PORT: ${POSTGRES_PORT:-5432}
      QUEUE_DB_POOL_SIZE: ${POSTGRES_POOL_SIZE:-30}

      # Queue Platform RabbitMQ
      JOB_QUEUE_USERNAME: ${QUEUE_USER:-rabbituser}
      JOB_QUEUE_PASSWORD: ${QUEUE_PASS}
      JOB_QUEUE_HOST: ${QUEUE_HOST:-queue}
      JOB_QUEUE_PORT: ${QUEUE_PORT:-5672}
      SLOW_QUEUE_NAME: ${QUEUE_SLOW_NAME:-slow-queue}
      SLOW_QUEUE_WORKERS: ${QUEUE_SLOW_WORKERS:-2}
      FAST_QUEUE_NAME: ${QUEUE_FAST_NAME:-fast-queue}
      FAST_QUEUE_WORKERS: ${QUEUE_FAST_WORKERS:-5}

      # Queue Platform Minio
      S3_HOST: ${S3_HOST}
      S3_PORT: ${S3_PORT:-443}
      S3_BUCKET: ${S3_BUCKET}
      S3_ACCESS_TOKEN: ${S3_ACCESS_TOKEN}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_USE_HTTPS: ${S3_USE_HTTPS:-true}

      # Job Settings
      JOB_CACHE_TIMEOUT_DAYS: 30

networks:
  internal:
    internal: true
