#%RAML 1.0 Library

types:
  PlainTextFastaResponse:
    type: string

  DeflineFormat:
    type: string
    enum: ["query_only", "region_only", "query_and_region"]
    default: "region_only"
    required: false

  Strand:
    type: string
    # enum: ['+', '-', '.'] gives errors
    default: '.'
    required: false

  Feature:
    additionalProperties: false
    properties:
      contig: string
      start: integer
      end: integer
      query?: string
      strand?: Strand

  FeaturesList: 
    additionalProperties: false
    properties:
      features:
        type: array
        items: Feature

  StartOffset:
    type: string
    enum: ["ZERO", "ONE"]

  FeaturesBed:
    additionalProperties: false
    properties:
      bed: file
      startOffset: StartOffset

  FeaturesGFF3:
    additionalProperties: false
    properties:
      gff3: file

  FeaturesData: FeaturesList | FeaturesBed | FeaturesGFF3
