#%RAML 1.0 Library

types:
  PlainTextFastaResponse:
    type: string

  DeflineFormat:
    type: string
    enum: ["query_only", "region_only", "query_and_region"]

  Feature:
    additionalProperties: false
    properties:
      contig: string
      start: integer
      end: integer
      query?: string
      strand?: string
