#%RAML 1.0 Library

types:
  PlainTextFastaResponse:
    type: string

  DeflineFormat:
    type: string
    enum: ["query_only", "region_only", "query_and_region"]
    default: "region_only"
    required: false

  Strand:
    type: string
    # enum: ['+', '-', '.'] gives errors
    default: '.'
    required: false

  Feature:
    additionalProperties: false
    properties:
      contig: string
      start: integer
      end: integer
      query?: string
      strand: Strand
