#%RAML 1.0 Library

types:

  PlainTextFastaResponse:
    # making this an object triggers generation of Response and ResponseStream mechanisms
    type: object

  DeflineFormat:
    type: string
    enum: ['QUERYONLY', 'REGIONONLY', 'QUERYANDREGION']

  Strand:
    type: string
    enum: ['POSITIVE', 'NEGATIVE', 'NONE']

  StartOffset:
    type: string
    enum: ['ZERO', 'ONE']

  UploadMethod:
    type: string
    enum: ['file', 'url']

  SupportedFileFormat:
    type: string
    enum: ['bed', 'gff3']

  Feature:
    additionalProperties: false
    properties:
      contig: string
      start: integer
      end: integer
      query?: string
      strand?:
        type: Strand
        default: 'NONE'

  SequencePostRequest:
    additionalProperties: false
    properties:
      features:
        type: array
        items: Feature
      deflineFormat?:
        type: DeflineFormat
        default: 'REGIONONLY'
      basesPerLine?:
        type: integer
        default: 60
      
  SequenceRetrievalSpec:
    additionalProperties: false
    properties:
      features:
        type: array
        items: Feature
      featuresStr:
        type: string
      featuresUrl:
        type: string
      fileFormat:
        type: SupportedFileFormat
      uploadMethod:
        type: UploadMethod
      startOffset:
        type: StartOffset
      deflineFormat:
        type: DeflineFormat
      basesPerLine:
        type: integer
      sequenceType:
        type: string
